server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Distributed tracing
management.tracing.sampling.probability=1.0

# Actuator
management.endpoints.web.exposure.include=*

# -------------------------
# Gateway - User Service
# -------------------------
spring.cloud.gateway.routes[0].id=userservice
spring.cloud.gateway.routes[0].uri=lb://FeignUserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Circuit Breaker
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=name=userServiceCB,fallbackUri=forward:/fallback/users

# Rate Limiter
spring.cloud.gateway.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[0].filters[1].args.key-resolver=#{@ipKeyResolver}

# -------------------------
# Gateway - Order Service
# -------------------------
spring.cloud.gateway.routes[1].id=orderservice
spring.cloud.gateway.routes[1].uri=lb://FeignOrderService
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**

# Circuit Breaker
spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=name=orderServiceCB,fallbackUri=forward:/fallback/orders

# Rate Limiter
spring.cloud.gateway.routes[1].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[1].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[1].filters[1].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[1].filters[1].args.key-resolver=#{@ipKeyResolver}

#Auth Route in Gateway
spring.cloud.gateway.routes[2].id=authservice
spring.cloud.gateway.routes[2].uri=lb://FeignUserService
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

# -------------------------
# Redis Configuration
# -------------------------
spring.redis.host=localhost
spring.redis.port=6379


#jwt config
jwt.secret=likhith-super-secure-jwt-key-likhith-super-secure-jwt-key
