server.port=8080

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Distributed logs
management.tracing.sampling.probability=1.0

#Gateway
spring.cloud.gateway.routes[0].id=userservice
spring.cloud.gateway.routes[0].uri=lb://FeignUserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=orderservice
spring.cloud.gateway.routes[1].uri=lb://FeignOrderService
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**

#CircuitBreaker
#This creates a circuit breaker instance. If service fails → redirect to fallback endpoint.
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=name=userServiceCB,fallbackUri=forward:/fallback/users
spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=name=orderServiceCB,fallbackUri=forward:/fallback/orders
