spring.application.name=FeignUserService
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/feign_db
spring.datasource.username=root
spring.datasource.password=SreeRama@005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Application logs
logging.level.root=INFO
logging.level.com.likhith=DEBUG

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Distributed Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Feign
spring.cloud.openfeign.lazy-attributes-resolution=true

# Trace log pattern
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name},%X{traceId},%X{spanId}] %logger{36} - %msg%n

#Resilience4j Config (Circuit Breaker)
resilience4j.circuitbreaker.instances.orderServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.orderServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.orderServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderServiceCB.permittedNumberOfCallsInHalfOpenState=3


# Retry Config
resilience4j.retry.instances.retryLogic.maxAttempts=3
resilience4j.retry.instances.retryLogic.waitDuration=2s
resilience4j.retry.instances.retryLogic.retryExceptions=java.io.IOException,feign.FeignException



